version: '3'
services:
    laravel:
        build: .
        restart: always
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            PORT: 80
        volumes:
            - '.:/app'
            - '$(pwd)/letsencrypt:/etc/letsencrypt'
            - '$(pwd)/docker/nginx.conf:/etc/nginx/nginx.conf'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    phpmyadmin:
        image: 'phpmyadmin'
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: 'mysql'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        restart: always
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
    memcached:
        image: 'memcached:alpine'
        restart: always
        ports:
            - '11211:11211'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        restart: always
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
